//VEMOS QUE EL ARCHIVO DE NUESTRO SOTRE YA ESTA CREADO CON TODA
//SU ESTRUCTURA, VAMOS A DEJAR SOLO MODULES, ESTO CON EL FIN DE
// HACER UN POCO MAS ORDENADO NUESTRO PROYECTO PUES
//VAMOS A CREAR UN MODULO, POR CADA UNA DE LAS SESIONES DE
//NUESTRO PROYECTO, EN ESTE CASO TENEMOS 3 SESIONES
//LA SESION DE LOGIN,GESTION DE AUTORES, Y GESTION DE LIBROS
//VAMOS A CREARLAS POR APARTE Y LUEGO LAS IMPORTAMOS DIRECTAMETE
//EN EL STORE
//RECORDEMOS QUE EL STORE LO IMPORTAMOS EN MAIN.JS Y LO ASOCIAMOS
//A LA INSTANCIA
//IR A MIRAR Y VOLVEMOS

//EXPLICADO ESTO VAMOS A VERIFICAR EL ROUTER.

import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  modules: {

  }
})
